### ISSUE TITLE
Conbee unreachable in homebridge-hue since installing homebridge-rpi

### ISSUE THREAD

**Issue by Jafalex** [ebaauw/homebridge-rpi#14]
Hi,
I just installed homebridge-pi to monitor temperature of my two Pi's. I followed the [Raspbery Pi Configuration guide](https://github.com/ebaauw/homebridge-rpi#Raspberry-Pi-Configuration) and got things working fine on both computers, first try.

However, upon restarting Homebridge, I get an error from Homebridge-hue in the Homebridge logs, as follow:

```
[3/6/2020, 11:38:28 AM] [Hue] ConbeeGW: error: /sensors/1: {"config":{"configured":true,"on":true,"sunriseoffset":30,"sunsetoffset":-30,"reachable":true},"etag":"2a2888d62308ddd6d2bd65da0e63c919","manufacturername":"Philips","modelid":"PHDL00","name":"Daylight","state":{"dark":true,"daylight":null,"lastupdated":"none","status":null,"lightlevel":0},"swversion":"1.0","type":"Daylight","uniqueid":"00:21:2e:ff:ff:05:02:26-01"}
 TypeError: Cannot read property 'period' of undefined
    at HueSensor.checkStatus (/homebridge/node_modules/homebridge-hue/lib/HueSensor.js:2035:48)
    at new HueSensor (/homebridge/node_modules/homebridge-hue/lib/HueSensor.js:1523:12)
    at HueAccessory.exposeSensorResource (/homebridge/node_modules/homebridge-hue/lib/HueAccessory.js:312:20)
    at HueAccessory.exposeSensorResources (/homebridge/node_modules/homebridge-hue/lib/HueAccessory.js:302:12)
    at HueAccessory.expose (/homebridge/node_modules/homebridge-hue/lib/HueAccessory.js:123:8)
    at HueBridge.exposeResources (/homebridge/node_modules/homebridge-hue/lib/HueBridge.js:534:49)
    at HueBridge.accessories (/homebridge/node_modules/homebridge-hue/lib/HueBridge.js:92:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async HuePlatform.accessories (/homebridge/node_modules/homebridge-hue/lib/HuePlatform.js:311:29)
```

More about my Hue config here (and quickly resolved bug): https://github.com/ebaauw/homebridge-hue/issues/636

Homebridge launches fine and is usable, however all homebridge-hue exposed devices fail to work, resulting in the following logs:
```
[3/6/2020, 11:44:23 AM] [Hue] ConbeeGW: gateway request 75: put /lights/1/state {"on":true}
[3/6/2020, 11:44:23 AM] [Hue] ConbeeGW: gateway communication error: resource, /lights/1, not available
```

Could the `pigpiod` and `vcgencmd` script have messed things up with Conbee II USB connections?

Note: I believe this plugin/config is definitely the culprit, as things were working fine an hour ago (and have been for days now).

Thanks!

**Comment by Jafalex** [comment]
Pays to add that deCONZ is running as expected

```
$ sudo systemctl status deconz                                                                                                                      
● deconz.service - deCONZ: ZigBee gateway -- REST API
   Loaded: loaded (/lib/systemd/system/deconz.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-03-06 11:57:38 NZDT; 10min ago
 Main PID: 367 (deCONZ)
    Tasks: 5 (limit: 4915)
   Memory: 37.9M
   CGroup: /system.slice/deconz.service
           └─367 /usr/bin/deCONZ -platform minimal --http-port=80

Mar 06 11:57:38 raspberrypi systemd[1]: Started deCONZ: ZigBee gateway -- REST API.
Mar 06 11:57:40 raspberrypi deCONZ[367]: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-pi'
Mar 06 11:57:41 raspberrypi deCONZ[367]: libpng warning: iCCP: known incorrect sRGB profile
Mar 06 11:57:42 raspberrypi deCONZ[367]: This plugin does not support propagateSizeHints()
Mar 06 11:57:42 raspberrypi deCONZ[367]: This plugin does not support propagateSizeHints()
Mar 06 11:57:52 raspberrypi deCONZ[367]: This plugin does not support propagateSizeHints()
```

**Comment by Jafalex** [comment]
Hi @ebaauw,

Yes, Homebridge is running in Docker on the same raspberry pi 4B that deCONZ is set up. deCONZ runs outside of Docker obviously.

I can see and control all the lights fine from the Phoscon web interface or the Hue Essentials iOS app. 

Yep, rebooted the Pi.

Is homebridge-rpi making use of http:8888 in any way?
Is it possible to undo all the steps of configuring `pigpiod` and from the `vcgencmd` script? I can't think of anything else...

**Comment by Jafalex** [comment]
Alright, all sorted.. Sorry for taking some of your time on this one. It seems it was a proximity issue with the bulbs, or maybe there's been some interferences from the neighbours at the wrong time, which made me believe the issue came from this newly installed plugin. 

Brought the bulbs closer to the Conbee upon rebooting the Pi, and all is good. Again, sorry for the time wasted here.
