### ISSUE TITLE
doesn't work with 8G memory Raspberry Pi 4B model

### ISSUE THREAD

**Issue by sjdy521** [ebaauw/homebridge-rpi#43]
run the command `rpi info` in a shell,  get this error :
```
rpi info: error: RangeError: 0x00D03114: unknown revision
    at Function.parseRevision (/usr/local/lib/node_modules/homebridge-rpi/lib/RpiInfo.js:157:13)
    at Function.parseCpuInfo (/usr/local/lib/node_modules/homebridge-rpi/lib/RpiInfo.js:126:25)
    at RpiInfo.getCpuInfo (/usr/local/lib/node_modules/homebridge-rpi/lib/RpiInfo.js:109:29)
    at async Main.info (/usr/local/lib/node_modules/homebridge-rpi/cli/rpi.js:182:14)
    at async Main.main (/usr/local/lib/node_modules/homebridge-rpi/cli/rpi.js:129:7)
```

![image](https://user-images.githubusercontent.com/7497148/87224094-0777a580-c3b5-11ea-9242-266634426c91.png)

I add some debug code to dump out `result` variable

```
{
  manufacturer: 'Sony UK',
  memory: undefined,
  model: '4B',
  processor: 'BCM2711',
  revision: '1.4'
}
```

it seems like this plugins doesn't fit the newest 8G memory Raspberry Pi model
 Hope we can fix this bug as soon as possible

**Comment by Sertingolix** [comment]
I experienced the same error. I'm lucky to not be the only one

**Comment by ebaauw** [comment]
Should work in v1.1.10.
