### ISSUE TITLE
Plugin RangeError

### ISSUE THREAD

**Issue by barryl93** [ebaauw/homebridge-rpi#55]
Hi! Tried connecting this to my Pi Zero W, which isn't running any GPIO stuff at all. (Just want to monitor the temperature for now.) But it keeps throwing an error that kills HB, then reboots it over and over.

Here's the pertinent part of the error log:

[8/29/2020, 7:17:28 PM] [RPi] 192.168.7.143: connected to 192.168.7.143:22
[8/29/2020, 7:17:28 PM] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 7. Received 12
    at boundsError (internal/buffer.js:77:9)
    at Buffer.readInt32LE (internal/buffer.js:381:5)
    at PigpioClient._onCmdData (/usr/local/lib/node_modules/homebridge-rpi/lib/PigpioClient.js:466:16)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
[8/29/2020, 7:17:28 PM] Got SIGTERM, shutting down Homebridge...

Not sure if I borked something by not adding a GPIO device or what...

**Comment by ebaauw** [comment]
What’s your config.json?  You seem to be connecting to`ssh` (port 22) instead of `pigpiod`.

**Comment by barryl93** [comment]
Ah, OK, this is my bad. Since I wasn't trying to pull anything from the GPIO, I thought I should just connect to SSH. I didn't give the installation instructions a third look and made some assumptions! When I hook it all back up again, I'll connect to pigpiod instead. (Can't show the config because I had to uninstall the plugin to keep it from restarting HB over and over.)

Thanks!
