### ISSUE TITLE
unknown revision 0x0100000D

### ISSUE THREAD

**Issue by Knight1** [ebaauw/homebridge-rpi#68]
Hi!

My Homebridge reports that my Rasperry Pi is unsupported

```
[11/22/2020, 1:35:26 AM] [RPi] NAME: connected to IP:8888
[11/22/2020, 1:35:26 AM] [RPi] warning: NAME: got file handle 1
[11/22/2020, 1:35:26 AM] [RPi] warning: NAME: RangeError: 0x0100000D: unknown revision
    at Function.parseRevision (/usr/lib/node_modules/homebridge-rpi/lib/RpiInfo.js:157:13)
    at Function.parseCpuInfo (/usr/lib/node_modules/homebridge-rpi/lib/RpiInfo.js:127:25)
    at RpiPlatform.checkDevice (/usr/lib/node_modules/homebridge-rpi/lib/RpiPlatform.js:236:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

```
root@raspberrypi:~# cat /proc/cpuinfo
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2835
Revision	: 100000d
Serial		: 00000000c0f62527
Model		: Raspberry Pi Model B Rev 2
```

```
root@raspberrypi:~# pigs hwver
13
```

Any ideas? According to https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md this is the correct revision.

000d | B | 2.0 | 512MB | Egoman
-- | -- | -- | -- | --

**Comment by ebaauw** [comment]
So what’s the `1` doing in `/proc/cpuinfo`?  `pigs hwver` does report 0x0D (13) correctly, without the `1`.

**Comment by Knight1** [comment]
```
[11/22/2020, 7:02:08 PM] [RPi] Flightradar: connected to IP:8888
[11/22/2020, 7:02:08 PM] [RPi] warning: Flightradar: got file handle 1
[11/22/2020, 7:02:08 PM] [RPi] Flightradar: Raspberry Pi B v2.0 (BCM2835, 512MB) - SN
[11/22/2020, 7:02:08 PM] [RPi] Flightradar: set Serial Number to "..."
[11/22/2020, 7:02:08 PM] [RPi] Flightradar: set Manufacturer to "Egoman"
[11/22/2020, 7:02:08 PM] [RPi] Flightradar: set Model to "Raspberry Pi B"
[11/22/2020, 7:02:08 PM] [RPi] Flightradar: set Hardware Revision to "2.0"
[11/22/2020, 7:02:08 PM] [RPi] Flightradar: set Temperature Display Units to 0
[11/22/2020, 7:02:08 PM] [RPi] Flightradar: set Heartrate to 15 seconds
[11/22/2020, 7:02:08 PM] [RPi] Flightradar: set Log Level to 2
[11/22/2020, 7:02:08 PM] [RPi] Flightradar: set Smoke Detected to 0
[11/22/2020, 7:02:23 PM] [RPi] Flightradar: warning: got file handle 1
[11/22/2020, 7:02:23 PM] [RPi] Flightradar: set Current Temperature to 31.5°C
[11/22/2020, 7:02:23 PM] [RPi] Flightradar: set Frequency to 700MHz
[11/22/2020, 7:02:23 PM] [RPi] Flightradar: set Voltage to 1.2V
[11/22/2020, 7:02:23 PM] [RPi] Flightradar: set Throttled to false
[11/22/2020, 7:02:23 PM] [RPi] Flightradar: set Under Voltage to false
[11/22/2020, 7:02:23 PM] [RPi] Flightradar: set Load to 1.19
[11/22/2020, 7:02:23 PM] [RPi] Flightradar: set Last Boot to "Wed Nov 04 2020 17:35:18"
[11/22/2020, 7:02:38 PM] [RPi] Flightradar: warning: got file handle 1
[11/22/2020, 7:02:38 PM] [RPi] Flightradar: set Load from 1.19 to 1
[11/22/2020, 7:02:53 PM] [RPi] Flightradar: warning: got file handle 1
[11/22/2020, 7:02:53 PM] [RPi] Flightradar: set Load from 1 to 1.28
```

Thank you!

**Comment by ebaauw** [comment]
In v1.2.1.
