### ISSUE TITLE
warning: Homebridge-RaspPi: TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by subcritical71** [ebaauw/homebridge-rpi#98]
I have recently installed your plugin but have not been able to get it to work properly.

Results of 'rpi info'
```
pi@homebridge:/var/lib/homebridge $ rpi info
{
  "id": "100000005A7718C0",
  "manufacturer": "Sony UK",
  "memory": "4GB",
  "model": "4B",
  "processor": "BCM2711",
  "revision": "1.4",
  "gpioMask": "0x0FFFFFFC",
  "gpioMaskSerial": "0x0000C000",
  "date": "2021-06-04T23:42:11.000Z",
  "boot": "2021-06-04T23:35:00.290Z",
  "powerLed": 0,
  "load": 0.1,
  "temp": 41.8,
  "freq": 600169920,
  "volt": 0.86,
  "throttled": "0x00050005"
}
```

config.json
```
            "name": "RPi",
            "hosts": [
                {
                    "host": "XX.XX.XX.XX:8888",
                    "name": "Homebridge-RaspPi",
                    "hidden": false,
                    "noSmokeSensor": false
                    ]
                },
```

I get a connection to the RPi, but this error occurs;

```
[04/06/2021, 19:40:18] [RPi] warning: Homebridge-RaspPi: TypeError: Cannot read property '1' of null
    at Function.parseCpuInfo (/usr/local/lib/node_modules/homebridge-rpi/lib/RpiInfo.js:135:57)
    at RpiPlatform.checkDevice (/usr/local/lib/node_modules/homebridge-rpi/lib/RpiPlatform.js:264:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at RpiPlatform.init (/usr/local/lib/node_modules/homebridge-rpi/lib/RpiPlatform.js:173:7)
    at RpiPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-rpi/lib/RpiPlatform.js:17:46)
```

**Comment by ebaauw** [comment]
The piece of config.json you show is invalid: the braces don’t match.

Are you trying to expose the local RPi, or connecting to a remote RPi.  In the first case, make sure to use `localhost` or `127.0.0.1` for the hostname.  If you specify a non-loopback IP address, make sure to configure `pigpiod` as for a remote RPi.  Homebridge RPi connects to the RPi remotely to retrieve the serialnumber.  If that matches the local serialnumber it will continue to access the RPi locally.

**Comment by subcritical71** [comment]
Looks like user error on my part.

I didn't read closely enough at your instructions and got the getStatus and access files wrong. (copied the whole code block).

But I did try the local (and 127.0.0.1) and the plugin didn't like it. So I went back to the IP address.

**Comment by ebaauw** [comment]
> But I did try the local (and 127.0.0.1) and the plugin didn't like it. So I went back to the IP address.

Probably issue #99.

**Comment by goliwok** [comment]
Same issue here:
```
[9/3/2021, 12:45:49 PM] [RPi] warning: raspberrypi: TypeError: Cannot read property '1' of null
    at Function.parseCpuInfo (/homebridge/node_modules/homebridge-rpi/lib/RpiInfo.js:136:57)
    at RpiPlatform.checkDevice (/homebridge/node_modules/homebridge-rpi/lib/RpiPlatform.js:274:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at RpiPlatform.init (/homebridge/node_modules/homebridge-rpi/lib/RpiPlatform.js:173:7)
    at RpiPlatform.<anonymous> (/homebridge/node_modules/homebridge-rpi/lib/RpiPlatform.js:17:46)`
```
Plugin settings:
```json
{
    "name": "RPi",
    "hosts": [
        {
            "host": "192.168.1.20",
            "name": "raspberrypi"
        }
    ],
    "platform": "RPi"
}
```

Do you have any clues to debug or fix it ?
Thanks
